
// This file has been generated by the GUI designer. Do not modify.
namespace FleetUI
{
	public partial class ScreenCaptureSelector
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.DrawingArea captureArea;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FleetUI.ScreenCaptureSelector
			this.Name = "FleetUI.ScreenCaptureSelector";
			this.Title = global::Mono.Unix.Catalog.GetString ("ScreenCaptureSelector");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child FleetUI.ScreenCaptureSelector.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.captureArea = new global::Gtk.DrawingArea ();
			this.captureArea.Name = "drawingarea1";
			this.vbox1.Add (this.captureArea);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.captureArea]));
			w1.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
