
// This file has been generated by the GUI designer. Do not modify.
namespace FleetUI
{
	public partial class ShareSelectionDialog
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action RefreshAction;
		
		private global::Gtk.Action RefreshListAction;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview4;
		
		private global::Gtk.MenuBar menubar3;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FleetUI.ShareSelectionDialog
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.RefreshAction = new global::Gtk.Action ("RefreshAction", global::Mono.Unix.Catalog.GetString ("Refresh"), null, null);
			this.RefreshAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Refresh");
			w1.Add (this.RefreshAction, null);
			this.RefreshListAction = new global::Gtk.Action ("RefreshListAction", global::Mono.Unix.Catalog.GetString ("Refresh List"), null, null);
			this.RefreshListAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Refresh List");
			w1.Add (this.RefreshListAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "FleetUI.ShareSelectionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child FleetUI.ShareSelectionDialog.VBox
			global::Gtk.VBox w2 = this.VBox;
			w2.Name = "dialog1_VBox";
			w2.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(1)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView ();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow.Add (this.treeview4);
			this.table2.Add (this.GtkScrolledWindow);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.GtkScrolledWindow]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			// Container child table2.Gtk.Table+TableChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar3\'><menu name=\'RefreshAction\' action=\'RefreshAction\'><m" +
			"enuitem name=\'RefreshListAction\' action=\'RefreshListAction\'/></menu></menubar></" +
			"ui>");
			this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
			this.menubar3.Name = "menubar3";
			this.table2.Add (this.menubar3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.menubar3]));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			w2.Add (this.table2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w2 [this.table2]));
			w6.Position = 0;
			// Internal child FleetUI.ShareSelectionDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "dialog1_ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonOk]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.RefreshListAction.Activated += new global::System.EventHandler (this.OnTableRefresh);
			this.buttonCancel.Activated += new global::System.EventHandler (this.OnCancel);
			this.buttonOk.Activated += new global::System.EventHandler (this.OnSelection);
		}
	}
}
