
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Action CaptureAction;
	
	private global::Gtk.Action DesktopAction;
	
	private global::Gtk.Action PortionAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Image displayImage;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.CaptureAction = new global::Gtk.Action ("CaptureAction", global::Mono.Unix.Catalog.GetString ("Capture"), null, null);
		this.CaptureAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Capture");
		w1.Add (this.CaptureAction, null);
		this.DesktopAction = new global::Gtk.Action ("DesktopAction", global::Mono.Unix.Catalog.GetString ("Desktop"), null, null);
		this.DesktopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Desktop");
		w1.Add (this.DesktopAction, null);
		this.PortionAction = new global::Gtk.Action ("PortionAction", global::Mono.Unix.Catalog.GetString ("Portion"), null, null);
		this.PortionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Portion");
		w1.Add (this.PortionAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Capture");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='OpenAction' action='OpenAction'/><menuitem name='AboutAction' action='AboutAction'/><separator/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='CaptureAction' action='CaptureAction'><menuitem name='DesktopAction' action='DesktopAction'/><menuitem name='PortionAction' action='PortionAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.displayImage = new global::Gtk.Image ();
		this.displayImage.Name = "displayImage";
		this.displayImage.Yalign = 0F;
		this.vbox1.Add (this.displayImage);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.displayImage]));
		w3.PackType = ((global::Gtk.PackType)(1));
		w3.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 499;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenAction.Activated += new global::System.EventHandler (this.OnOpen);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAbout);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnExit);
		this.DesktopAction.Activated += new global::System.EventHandler (this.OnCaptureDesktop);
		this.PortionAction.Activated += new global::System.EventHandler (this.OnPortion);
	}
}
